package com.bloxbean.cardano.zeroj.verifier.halo2;

import com.bloxbean.cardano.zeroj.api.*;
import com.bloxbean.cardano.zeroj.backend.spi.InMemoryVerificationKeyRegistry;
import com.bloxbean.cardano.zeroj.verifier.core.VerifierOrchestrator;
import com.bloxbean.cardano.zeroj.verifier.core.VerifierRegistry;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for Halo2 IPA verification via Rust FFM.
 * <p>
 * Uses real Halo2 proofs generated by the Rust library for the multiplier circuit (3*11=33).
 * Tests are skipped if the native library is not available.
 */
@EnabledIf("isNativeLibraryAvailable")
class Halo2VerifierTest {

    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static Halo2Library library;
    private static String resultJson;

    @BeforeAll
    static void setup() throws Exception {
        library = new Halo2Library();
        // Generate a fresh proof (setup + prove in one call)
        resultJson = library.setupAndProve(4, 3, 11); // 3 * 11 = 33
        assertNotNull(resultJson);
    }

    @Test
    void version_returnsValidString() {
        String version = library.version();
        assertNotNull(version);
        assertTrue(version.contains("halo2"), "Version should contain 'halo2': " + version);
        System.out.println("Halo2 version: " + version);
    }

    @Test
    void setupAndProve_generatesValidProof() throws Exception {
        JsonNode root = MAPPER.readTree(resultJson);

        assertEquals("halo2", root.get("protocol").asText());
        assertEquals("pallas", root.get("curve").asText());
        assertEquals("IPA", root.get("commitmentScheme").asText());
        assertFalse(root.get("trustedSetup").asBoolean(), "IPA should have NO trusted setup");
        assertTrue(root.get("verified").asBoolean(), "Proof should be verified in Rust");
        assertTrue(root.get("proofSize").asInt() > 0);
        assertTrue(root.get("paramsSize").asInt() > 0);

        assertEquals("33", root.get("publicInputs").get(0).asText());

        System.out.println("Halo2 proof generated:");
        System.out.println("  Proof size: " + root.get("proofSize").asInt() + " bytes");
        System.out.println("  Params size: " + root.get("paramsSize").asInt() + " bytes");
        System.out.println("  Trusted setup: " + root.get("trustedSetup").asBoolean());
        System.out.println("  Public input Z = " + root.get("publicInputs").get(0).asText());
    }

    @Test
    void verify_validProof_succeeds() throws Exception {
        JsonNode root = MAPPER.readTree(resultJson);

        byte[] proof = Base64.getDecoder().decode(root.get("proof").asText());
        byte[] params = Base64.getDecoder().decode(root.get("params").asText());

        boolean valid = library.verify(params, new byte[0], proof, "[\"33\"]");
        assertTrue(valid, "Valid Halo2 proof should verify");
    }

    @Test
    void verify_wrongPublicInput_fails() throws Exception {
        JsonNode root = MAPPER.readTree(resultJson);

        byte[] proof = Base64.getDecoder().decode(root.get("proof").asText());
        byte[] params = Base64.getDecoder().decode(root.get("params").asText());

        boolean valid = library.verify(params, new byte[0], proof, "[\"99\"]");
        assertFalse(valid, "Wrong public input should fail verification");
    }

    @Test
    void verify_tamperedProof_fails() throws Exception {
        JsonNode root = MAPPER.readTree(resultJson);

        byte[] proof = Base64.getDecoder().decode(root.get("proof").asText());
        byte[] params = Base64.getDecoder().decode(root.get("params").asText());

        // Tamper the proof
        proof[10] ^= (byte) 0xFF;
        boolean valid = library.verify(params, new byte[0], proof, "[\"33\"]");
        assertFalse(valid, "Tampered proof should fail verification");
    }

    @Test
    void spiVerifier_routesThroughOrchestrator() throws Exception {
        // Register Halo2 verifier in the SPI
        var registry = VerifierRegistry.empty();
        registry.register(new Halo2Verifier(library));
        var vkRegistry = new InMemoryVerificationKeyRegistry();
        var orchestrator = new VerifierOrchestrator(registry, vkRegistry);

        // Build envelope using Halo2Codec
        var envelope = com.bloxbean.cardano.zeroj.codec.Halo2Codec.toEnvelopeFromJson(
                resultJson, new CircuitId("halo2-multiplier"));

        assertEquals(ProofSystemId.HALO2, envelope.proofSystem());
        assertEquals(CurveId.PALLAS, envelope.curve());

        var material = VerificationMaterial.of(new byte[]{1},
                ProofSystemId.HALO2, CurveId.PALLAS, new CircuitId("halo2-multiplier"));

        // Verify through orchestrator — routes to Halo2Verifier via SPI
        VerificationResult result = orchestrator.verify(envelope, material);
        assertTrue(result.proofValid(),
                "Halo2 proof should verify through orchestrator: " + result.message().orElse(""));

        System.out.println("Halo2 IPA proof verified via VerifierOrchestrator (SPI routing)");
        System.out.println("  No trusted setup — IPA is transparent!");
    }

    @Test
    void endToEnd_setupProveVerify() {
        System.out.println("=== Halo2 End-to-End: Setup -> Prove -> Verify ===");
        System.out.println("Circuit: Multiplier (3 * 11 = 33)");
        System.out.println("Commitment: IPA (Inner Product Argument)");
        System.out.println("Curve: Pallas (Pasta cycle)");
        System.out.println("Trusted setup: NONE (transparent!)");
        System.out.println();

        // Fresh setup+prove
        String json = library.setupAndProve(4, 7, 5); // 7 * 5 = 35
        assertNotNull(json, "setupAndProve should return non-null");
        System.out.println("E2E result (first 300 chars): " + json.substring(0, Math.min(300, json.length())));
        assertTrue(json.contains("verified"), "Should contain 'verified' field");

        System.out.println("1. SETUP: IPA params generated (no ceremony needed)");
        System.out.println("2. PROVE: Halo2 proof for 7 * 5 = 35");
        System.out.println("3. VERIFY: Proof verified in Rust (sanity check)");
        System.out.println();
        System.out.println("Key advantage over Groth16/PlonK: NO TRUSTED SETUP");
        System.out.println("Anyone can verify params are correctly generated");
    }

    static boolean isNativeLibraryAvailable() {
        return Halo2NativeLoader.isAvailable();
    }
}
