package com.bloxbean.cardano.zeroj.onchain.julc;

import com.bloxbean.cardano.zeroj.bls12381.ec.JacobianG1BLS381;
import com.bloxbean.cardano.zeroj.bls12381.ec.JacobianG2BLS381;
import com.bloxbean.cardano.zeroj.crypto.groth16.Groth16ProofBLS381;
import com.bloxbean.cardano.zeroj.crypto.setup.Groth16SetupBLS381;
import supranational.blst.P1_Affine;
import supranational.blst.P2_Affine;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * Converts pure Java BLS12-381 prover output to compressed BLS point bytes
 * suitable for Cardano on-chain use (UPLC BLS12-381 builtins).
 *
 * <p>Bridges {@code zeroj-crypto} prover types to the on-chain Plutus V3
 * verifier in this module. Sibling of {@link SnarkjsToCardano}, which performs
 * the same conversion from snarkjs JSON output.</p>
 *
 * <p><b>For production:</b> Use this to convert proofs generated by the pure Java
 * prover ({@code Groth16ProverBLS381}) into the byte format expected by the
 * on-chain verifiers ({@link Groth16BLS12381Verifier} and
 * {@link Groth16BLS12381GenericVerifier}).</p>
 */
public final class ProverToCardano {

    private static final int FP_SIZE = 48;

    private ProverToCardano() {}

    /**
     * Compress a G1 affine point to 48-byte compressed BLS format.
     */
    public static byte[] g1Compress(JacobianG1BLS381.AffineG1 point) {
        if (point.isInfinity()) {
            // Compressed infinity: all zeros with the infinity flag set
            byte[] result = new byte[FP_SIZE];
            result[0] = (byte) 0xC0; // compressed + infinity flags
            return result;
        }
        byte[] uncompressed = new byte[FP_SIZE * 2]; // 96 bytes
        writeFp(uncompressed, 0, point.xBigInt());
        writeFp(uncompressed, FP_SIZE, point.yBigInt());
        return new P1_Affine(uncompressed).compress();
    }

    /**
     * Compress a G2 affine point to 96-byte compressed BLS format.
     *
     * <p>blst ordering: imaginary (c1) first, then real (c0) for each coordinate.</p>
     */
    public static byte[] g2Compress(JacobianG2BLS381.AffineG2 point) {
        if (point.isInfinity()) {
            byte[] result = new byte[FP_SIZE * 2];
            result[0] = (byte) 0xC0;
            return result;
        }
        byte[] uncompressed = new byte[FP_SIZE * 4]; // 192 bytes
        // blst: imaginary (c1) first, then real (c0)
        writeFp(uncompressed, 0, point.x().imBigInt());
        writeFp(uncompressed, FP_SIZE, point.x().reBigInt());
        writeFp(uncompressed, FP_SIZE * 2, point.y().imBigInt());
        writeFp(uncompressed, FP_SIZE * 3, point.y().reBigInt());
        return new P2_Affine(uncompressed).compress();
    }

    /**
     * Compress a Groth16 proof from prover output to on-chain format.
     */
    public static SnarkjsToCardano.ProofCompressed compressProof(Groth16ProofBLS381 proof) {
        return new SnarkjsToCardano.ProofCompressed(
                g1Compress(proof.a()),
                g2Compress(proof.b()),
                g1Compress(proof.c()));
    }

    /**
     * Compress VK components from setup result to on-chain format.
     *
     * @param setup  the setup result containing proving key + gammaG2 + IC points
     * @return compressed VK suitable for loading into the on-chain Julc verifier
     */
    public static SnarkjsToCardano.VkCompressed compressVk(Groth16SetupBLS381.SetupResult setup) {
        var pk = setup.provingKey();
        byte[] alpha = g1Compress(pk.alphaG1());
        byte[] beta = g2Compress(pk.betaG2());
        byte[] gamma = g2Compress(setup.gammaG2());
        byte[] delta = g2Compress(pk.deltaG2());

        List<byte[]> ic = new ArrayList<>();
        for (var icPoint : setup.ic()) {
            ic.add(g1Compress(icPoint));
        }

        return new SnarkjsToCardano.VkCompressed(alpha, beta, gamma, delta, ic);
    }

    /**
     * Write a field element as 48-byte big-endian into buffer at offset.
     */
    private static void writeFp(byte[] buf, int offset, BigInteger value) {
        byte[] bytes = value.toByteArray();
        int srcStart = Math.max(0, bytes.length - FP_SIZE);
        int count = Math.min(bytes.length, FP_SIZE);
        int destStart = offset + FP_SIZE - count;
        System.arraycopy(bytes, srcStart, buf, destStart, count);
    }
}
