package com.bloxbean.cardano.zeroj.crypto.groth16;

import com.bloxbean.cardano.zeroj.crypto.ec.JacobianG1BLS381;
import com.bloxbean.cardano.zeroj.crypto.ec.JacobianG2BLS381;
import com.bloxbean.cardano.zeroj.codec.SnarkjsJsonCodec;
import com.bloxbean.cardano.zeroj.verifier.groth16.bls12381.field.*;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.math.BigInteger;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-end test: snarkjs BLS12-381 .zkey + .wtns → pure Java prove → pairing verify.
 *
 * <p>This is the definitive snarkjs interoperability test. Uses real .zkey files
 * generated by {@code snarkjs groth16 setup --curve bls12381}.</p>
 */
class Groth16BLS381ZkeyEndToEndTest {

    private static final String MULT_ZKEY = "/test-circuits/multiplier-bls381/multiplier.zkey";
    private static final String MULT_WTNS = "/test-circuits/multiplier-bls381/witness.wtns";
    private static final String MULT_VK = "/test-circuits/multiplier-bls381/verification_key.json";

    private static final String CUBIC_ZKEY = "/test-circuits/cubic-bls381/cubic.zkey";
    private static final String CUBIC_WTNS = "/test-circuits/cubic-bls381/witness.wtns";
    private static final String CUBIC_VK = "/test-circuits/cubic-bls381/verification_key.json";

    @Test
    void multiplier_importZkey_proveAndPairingVerify() throws IOException {
        // Step 1: Import BLS12-381 .zkey
        var zkeyData = ZkeyImporterBLS381.importZkeyFull(
                getClass().getResourceAsStream(MULT_ZKEY).readAllBytes());
        var pk = zkeyData.provingKey();

        assertTrue(pk.alphaG1().isOnCurve(), "alpha on BLS12-381 G1");
        assertTrue(pk.betaG2().isOnCurve(), "beta on BLS12-381 G2");
        assertTrue(pk.deltaG1().isOnCurve(), "delta on BLS12-381 G1");
        assertTrue(pk.deltaG2().isOnCurve(), "delta on BLS12-381 G2");

        // Step 2: Import .wtns
        var witness = ZkeyImporterBLS381.importWtns(getClass().getResourceAsStream(MULT_WTNS));
        assertEquals(BigInteger.ONE, witness[0], "witness[0] = 1");
        assertEquals(BigInteger.valueOf(33), witness[1], "c = 33 (a=3, b=11)");

        // Step 3: PROVE with pure Java BLS381 prover
        var proof = Groth16ProverBLS381.prove(pk, witness,
                zkeyData.constraints(), zkeyData.numWires());

        assertNotNull(proof);
        assertTrue(proof.a().isOnCurve(), "Proof A on curve");
        assertTrue(proof.b().isOnCurve(), "Proof B on curve");
        assertTrue(proof.c().isOnCurve(), "Proof C on curve");

        // Step 4: VERIFY via BLS12-381 pairing check using VK from snarkjs
        var vkJson = new String(getClass().getResourceAsStream(MULT_VK).readAllBytes());
        var vk = SnarkjsJsonCodec.parseVerificationKey(vkJson);

        var piA = toG1(proof.a());
        var piB = toG2(proof.b());
        var piC = toG1(proof.c());

        var alpha = parseG1(vk.vkAlpha1());
        var beta = parseG2(vk.vkBeta2());
        var gamma = parseG2(vk.vkGamma2());
        var delta = parseG2(vk.vkDelta2());

        // vk_x = IC[0] + sum(pub_i * IC[i+1])
        var ic = vk.ic();
        G1Point vkX = parseG1(ic.get(0));
        BigInteger[] pubInputs = {BigInteger.valueOf(33)}; // c=33
        for (int i = 0; i < pubInputs.length; i++) {
            vkX = vkX.add(parseG1(ic.get(i + 1)).scalarMul(pubInputs[i]));
        }

        // e(A, B) * e(-alpha, beta) * e(-vk_x, gamma) * e(-C, delta) == 1
        boolean verified = BLS12381Pairing.pairingCheck(
                new G1Point[]{piA, alpha.negate(), vkX.negate(), piC.negate()},
                new G2Point[]{piB, beta, gamma, delta});

        assertTrue(verified, "BLS12-381 Groth16 pairing verification with snarkjs .zkey MUST pass");
        System.out.println("Multiplier: snarkjs BLS12-381 .zkey → Java prove → pairing verify PASSED!");
    }

    @Test
    void cubicCircuit_importZkey_proveAndPairingVerify() throws IOException {
        // Cubic: y = x^3 + x + 5, with x=3 → y=35
        var zkeyData = ZkeyImporterBLS381.importZkeyFull(
                getClass().getResourceAsStream(CUBIC_ZKEY).readAllBytes());
        var pk = zkeyData.provingKey();

        assertTrue(zkeyData.numConstraints() > 1, "Cubic has multiple constraints");

        var witness = ZkeyImporterBLS381.importWtns(getClass().getResourceAsStream(CUBIC_WTNS));
        assertEquals(BigInteger.ONE, witness[0]);
        assertEquals(BigInteger.valueOf(35), witness[1], "y = 3^3 + 3 + 5 = 35");

        // PROVE
        var proof = Groth16ProverBLS381.prove(pk, witness,
                zkeyData.constraints(), zkeyData.numWires());
        assertTrue(proof.a().isOnCurve());
        assertTrue(proof.b().isOnCurve());
        assertTrue(proof.c().isOnCurve());

        // VERIFY
        var vkJson = new String(getClass().getResourceAsStream(CUBIC_VK).readAllBytes());
        var vk = SnarkjsJsonCodec.parseVerificationKey(vkJson);

        var piA = toG1(proof.a());
        var piB = toG2(proof.b());
        var piC = toG1(proof.c());

        var alpha = parseG1(vk.vkAlpha1());
        var beta = parseG2(vk.vkBeta2());
        var gamma = parseG2(vk.vkGamma2());
        var delta = parseG2(vk.vkDelta2());

        var ic = vk.ic();
        G1Point vkX = parseG1(ic.get(0));
        BigInteger[] pubInputs = {BigInteger.valueOf(35)};
        for (int i = 0; i < pubInputs.length; i++) {
            vkX = vkX.add(parseG1(ic.get(i + 1)).scalarMul(pubInputs[i]));
        }

        boolean verified = BLS12381Pairing.pairingCheck(
                new G1Point[]{piA, alpha.negate(), vkX.negate(), piC.negate()},
                new G2Point[]{piB, beta, gamma, delta});

        assertTrue(verified, "BLS12-381 cubic circuit pairing verification MUST pass");
        System.out.println("Cubic: snarkjs BLS12-381 .zkey → Java prove → pairing verify PASSED!");
    }

    // --- Helpers ---

    private static G1Point toG1(JacobianG1BLS381.AffineG1 p) {
        if (p.isInfinity()) return G1Point.INFINITY;
        return new G1Point(Fp.of(p.xBigInt()), Fp.of(p.yBigInt()));
    }

    private static G2Point toG2(JacobianG2BLS381.AffineG2 p) {
        if (p.isInfinity()) return G2Point.INFINITY;
        return new G2Point(
                Fp2.of(Fp.of(p.x().reBigInt()), Fp.of(p.x().imBigInt())),
                Fp2.of(Fp.of(p.y().reBigInt()), Fp.of(p.y().imBigInt())));
    }

    private static G1Point parseG1(java.util.List<BigInteger> coords) {
        return new G1Point(Fp.of(coords.get(0)), Fp.of(coords.get(1)));
    }

    private static G2Point parseG2(java.util.List<java.util.List<BigInteger>> coords) {
        return new G2Point(
                Fp2.of(Fp.of(coords.get(0).get(0)), Fp.of(coords.get(0).get(1))),
                Fp2.of(Fp.of(coords.get(1).get(0)), Fp.of(coords.get(1).get(1))));
    }
}
