package com.bloxbean.cardano.zeroj.onchain.julc;

import com.bloxbean.cardano.zeroj.api.CurveId;
import com.bloxbean.cardano.zeroj.circuit.CircuitBuilder;
import com.bloxbean.cardano.zeroj.bls12381.ec.JacobianG1BLS381;
import com.bloxbean.cardano.zeroj.bls12381.ec.JacobianG2BLS381;
import com.bloxbean.cardano.zeroj.crypto.groth16.Groth16ProverBLS381;
import com.bloxbean.cardano.zeroj.crypto.groth16.Groth16ProofBLS381;
import com.bloxbean.cardano.zeroj.crypto.setup.Groth16SetupBLS381;
import com.bloxbean.cardano.zeroj.crypto.setup.PowersOfTauBLS381;
import com.bloxbean.cardano.julc.core.PlutusData;
import com.bloxbean.cardano.julc.testkit.ContractTest;
import com.bloxbean.cardano.julc.testkit.TestDataBuilder;
import org.junit.jupiter.api.Test;
import supranational.blst.P1_Affine;
import supranational.blst.P2_Affine;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * On-chain verification of proofs generated by the pure Java BLS12-381 prover.
 *
 * <p>Pipeline: Java DSL circuit → pure Java prove → compress → Julc VM Plutus V3 verify.</p>
 *
 * <p><b>DEV/TEST ONLY</b>: Uses single-party PowersOfTau. For production, use MPC ceremony.</p>
 */
class Groth16BLS12381PureJavaProverTest extends ContractTest {

    /**
     * 2-public-input circuit: pure Java prove → on-chain Julc VM verify.
     *
     * <p>Uses the generic {@link Groth16BLS12381Verifier} which requires exactly
     * 2 public inputs (3 IC points: IC[0], IC[1], IC[2]).</p>
     *
     * <p>Circuit: publicA * secretB = publicC (publicA and publicC are public).</p>
     */
    @Test
    void twoPublicInputs_pureJavaProve_onChainVerify() {
        // Circuit: a * b = c, where a and c are public, b is secret
        var circuit = CircuitBuilder.create("two-pub-mul")
                .publicVar("a").publicVar("c").secretVar("b")
                .define(api -> api.assertEqual(api.mul(api.var("a"), api.var("b")), api.var("c")));

        var r1cs = circuit.compileR1CS(CurveId.BLS12_381);
        assertEquals(2, r1cs.numPublicInputs(), "Must have exactly 2 public inputs for generic verifier");

        var constraints = r1cs.constraints();

        // Witness: a=3, b=11, c=33
        BigInteger[] witness = circuit.calculateWitness(Map.of(
                "a", List.of(BigInteger.valueOf(3)),
                "b", List.of(BigInteger.valueOf(11)),
                "c", List.of(BigInteger.valueOf(33))), CurveId.BLS12_381);

        // Dev setup + prove
        var srs = PowersOfTauBLS381.generate(4);
        var setupResult = Groth16SetupBLS381.setup(constraints, r1cs.numWires(),
                r1cs.numPublicInputs(), srs.tauScalar());

        var proof = Groth16ProverBLS381.prove(setupResult.provingKey(), witness,
                constraints, r1cs.numWires());

        assertTrue(proof.a().isOnCurve());
        assertTrue(proof.b().isOnCurve());
        assertTrue(proof.c().isOnCurve());

        // Compress VK + proof for on-chain
        var compressedVk = compressVk(setupResult);
        var compressedProof = compressProof(proof);

        assertEquals(3, compressedVk.ic().size(), "IC should have numPublic+1 = 3 entries");

        // Compile on-chain verifier with VK params
        var compiled = compileValidator(Groth16BLS12381Verifier.class);
        var program = compiled.program().applyParams(
                PlutusData.bytes(compressedVk.alpha()),
                PlutusData.bytes(compressedVk.beta()),
                PlutusData.bytes(compressedVk.gamma()),
                PlutusData.bytes(compressedVk.delta()),
                PlutusData.bytes(compressedVk.ic().get(0)),
                PlutusData.bytes(compressedVk.ic().get(1)),
                PlutusData.bytes(compressedVk.ic().get(2)));

        // Datum: 2 public inputs [a=3, c=33]
        var datum = PlutusData.list(
                PlutusData.integer(witness[1]),  // a=3
                PlutusData.integer(witness[2])); // c=33

        // Redeemer: compressed proof
        var redeemer = PlutusData.constr(0,
                PlutusData.bytes(compressedProof.piA()),
                PlutusData.bytes(compressedProof.piB()),
                PlutusData.bytes(compressedProof.piC()));

        var txOutRef = TestDataBuilder.randomTxOutRef_typed();
        var ctx = spendingContext(txOutRef, datum).redeemer(redeemer).buildPlutusData();

        var result = evaluate(program, ctx);
        assertSuccess(result);
        System.out.println("Pure Java prove → Julc VM on-chain verify PASSED");
        System.out.println("  Budget: " + result.budgetConsumed());
    }

    // --- BLS point compression using blst ---

    private static final int FP_SIZE = 48;

    private static SnarkjsToCardano.VkCompressed compressVk(Groth16SetupBLS381.SetupResult setup) {
        var pk = setup.provingKey();
        List<byte[]> ic = new ArrayList<>();
        for (var icPoint : setup.ic()) ic.add(g1Compress(icPoint));
        return new SnarkjsToCardano.VkCompressed(
                g1Compress(pk.alphaG1()), g2Compress(pk.betaG2()),
                g2Compress(setup.gammaG2()), g2Compress(pk.deltaG2()), ic);
    }

    private static SnarkjsToCardano.ProofCompressed compressProof(Groth16ProofBLS381 proof) {
        return new SnarkjsToCardano.ProofCompressed(
                g1Compress(proof.a()), g2Compress(proof.b()), g1Compress(proof.c()));
    }

    private static byte[] g1Compress(JacobianG1BLS381.AffineG1 p) {
        if (p.isInfinity()) { byte[] r = new byte[FP_SIZE]; r[0] = (byte) 0xC0; return r; }
        byte[] u = new byte[FP_SIZE * 2];
        writeFp(u, 0, p.xBigInt());
        writeFp(u, FP_SIZE, p.yBigInt());
        return new P1_Affine(u).compress();
    }

    private static byte[] g2Compress(JacobianG2BLS381.AffineG2 p) {
        if (p.isInfinity()) { byte[] r = new byte[FP_SIZE * 2]; r[0] = (byte) 0xC0; return r; }
        byte[] u = new byte[FP_SIZE * 4];
        writeFp(u, 0, p.x().imBigInt()); writeFp(u, FP_SIZE, p.x().reBigInt());
        writeFp(u, FP_SIZE * 2, p.y().imBigInt()); writeFp(u, FP_SIZE * 3, p.y().reBigInt());
        return new P2_Affine(u).compress();
    }

    private static void writeFp(byte[] buf, int offset, BigInteger value) {
        byte[] bytes = value.toByteArray();
        int srcStart = Math.max(0, bytes.length - FP_SIZE);
        int count = Math.min(bytes.length, FP_SIZE);
        System.arraycopy(bytes, srcStart, buf, offset + FP_SIZE - count, count);
    }
}
