package com.bloxbean.cardano.zeroj.verifier.plonk;

import com.bloxbean.cardano.zeroj.api.*;
import com.bloxbean.cardano.zeroj.backend.spi.ZkVerifier;
import com.bloxbean.cardano.zeroj.codec.SnarkjsPlonkCodec;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.ServiceLoader;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests for PlonK BN254 verifier using real snarkjs test vectors.
 *
 * <p>Uses the multiplier circuit test vectors generated by snarkjs PlonK (BN254).
 * Circuit: a * b = c, with a=3 (public), b=11 (private), c=33 (public).</p>
 */
class PlonkBN254VerifierTest {

    private String proofJson;
    private String vkJson;
    private String publicJson;
    private PlonkBN254Verifier verifier;

    @BeforeEach
    void setUp() {
        proofJson = loadString("/test-vectors/plonk-bn254/proof.json");
        vkJson = loadString("/test-vectors/plonk-bn254/verification_key.json");
        publicJson = loadString("/test-vectors/plonk-bn254/public.json");
        verifier = new PlonkBN254Verifier();
    }

    @AfterEach
    void clearLegacyBn254OptIn() {
        System.clearProperty(LegacyCurvePolicy.ALLOW_LEGACY_BN254_PROPERTY);
    }

    @Test
    void descriptor_correctProofSystemAndCurve() {
        var descriptor = verifier.descriptor();
        assertEquals(ProofSystemId.PLONK, descriptor.proofSystem());
        assertEquals(CurveId.BN254, descriptor.curve());
        assertTrue(descriptor.supports(ProofSystemId.PLONK, CurveId.BN254));
        assertFalse(descriptor.supports(ProofSystemId.GROTH16, CurveId.BN254));
    }

    @Test
    void verify_disabledByDefault() {
        var envelope = buildEnvelope(proofJson, vkJson, publicJson);
        var material = buildMaterial(vkJson);

        var result = verifier.verify(envelope, material);

        assertFalse(result.proofValid());
        assertEquals(VerificationResult.ReasonCode.UNSUPPORTED_CURVE, result.reasonCode().orElseThrow());
    }

    @Test
    void serviceLoaderDoesNotRegisterBn254() {
        boolean registered = ServiceLoader.load(ZkVerifier.class).stream()
                .map(ServiceLoader.Provider::get)
                .anyMatch(verifier -> verifier.descriptor().supports(ProofSystemId.PLONK, CurveId.BN254));

        assertFalse(registered, "BN254 PlonK verifier must not be auto-registered");
    }

    @Test
    void verify_realSnarkjsProof_validProofAccepted() {
        enableLegacyBn254();
        var envelope = buildEnvelope(proofJson, vkJson, publicJson);
        var material = buildMaterial(vkJson);

        var result = verifier.verify(envelope, material);

        assertNotNull(result);
        assertTrue(result.proofValid(), "Valid snarkjs PlonK BN254 proof should pass: "
                + result.message().orElse("no message"));
    }

    @Test
    void verify_tamperedEvaluation_rejected() {
        enableLegacyBn254();
        // Tamper with an evaluation to produce an invalid proof
        String tampered = proofJson.replace("\"eval_a\":", "\"eval_a\": \"999\", \"_old_eval_a\":");
        var envelope = ZkProofEnvelope.builder()
                .proofSystem(ProofSystemId.PLONK).curve(CurveId.BN254)
                .circuitId(new CircuitId("multiplier"))
                .proofBytes(tampered.getBytes(StandardCharsets.UTF_8))
                .publicInputs(com.bloxbean.cardano.zeroj.codec.SnarkjsJsonCodec.parsePublicInputs(publicJson))
                .vkRef(new VerificationKeyRef.ByHash(new byte[32]))
                .proofFormat("snarkjs-plonk-json").build();
        var material = buildMaterial(vkJson);

        var result = verifier.verify(envelope, material);
        assertFalse(result.proofValid(), "Tampered proof should fail");
    }

    @Test
    void verify_wrongPublicInputCount_rejectsEarly() {
        enableLegacyBn254();
        // Build envelope with wrong number of public inputs
        var inputs = new PublicInputs(java.util.List.of(BigInteger.valueOf(33)));
        var envelope = ZkProofEnvelope.builder()
                .proofSystem(ProofSystemId.PLONK)
                .curve(CurveId.BN254)
                .circuitId(new CircuitId("multiplier"))
                .proofBytes(proofJson.getBytes(StandardCharsets.UTF_8))
                .publicInputs(inputs)
                .vkRef(new VerificationKeyRef.ByHash(new byte[32]))
                .proofFormat("snarkjs-plonk-json")
                .build();
        var material = buildMaterial(vkJson);

        var result = verifier.verify(envelope, material);
        assertFalse(result.proofValid());
        assertEquals(VerificationResult.ReasonCode.INVALID_PUBLIC_INPUTS, result.reasonCode().orElse(null));
    }

    @Test
    void verify_malformedProof_returnsError() {
        enableLegacyBn254();
        var envelope = ZkProofEnvelope.builder()
                .proofSystem(ProofSystemId.PLONK)
                .curve(CurveId.BN254)
                .circuitId(new CircuitId("multiplier"))
                .proofBytes("not valid json".getBytes(StandardCharsets.UTF_8))
                .publicInputs(new PublicInputs(java.util.List.of(BigInteger.ONE)))
                .vkRef(new VerificationKeyRef.ByHash(new byte[32]))
                .build();
        var material = buildMaterial(vkJson);

        var result = verifier.verify(envelope, material);
        assertFalse(result.proofValid());
        assertEquals(VerificationResult.ReasonCode.INTERNAL_ERROR, result.reasonCode().orElse(null));
    }

    @Test
    void verify_sameProofTwice_deterministic() {
        enableLegacyBn254();
        var envelope = buildEnvelope(proofJson, vkJson, publicJson);
        var material = buildMaterial(vkJson);

        var r1 = verifier.verify(envelope, material);
        var r2 = verifier.verify(envelope, material);

        assertEquals(r1.proofValid(), r2.proofValid(), "same proof must produce same result");
        assertTrue(r1.proofValid());
    }

    @Test
    void vanishingPolynomial_evaluatesCorrectly() {
        var vk = SnarkjsPlonkCodec.parseVerificationKey(vkJson);
        BigInteger bn254_r = new BigInteger(
                "21888242871839275222246405745257275088548364400416034343698204186575808495617");
        int n = vk.domainSize();
        BigInteger omega = vk.w();

        // omega^n = 1 (already tested in codec, but verify here too)
        assertEquals(BigInteger.ONE, omega.modPow(BigInteger.valueOf(n), bn254_r));

        // Z_H(omega) = omega^n - 1 = 0 (vanishing polynomial vanishes on domain)
        BigInteger zh_at_omega = omega.modPow(BigInteger.valueOf(n), bn254_r)
                .subtract(BigInteger.ONE).mod(bn254_r);
        assertEquals(BigInteger.ZERO, zh_at_omega);
    }

    @Test
    void lagrangePolynomial_L1_sumsCorrectly() {
        var vk = SnarkjsPlonkCodec.parseVerificationKey(vkJson);
        BigInteger bn254_r = new BigInteger(
                "21888242871839275222246405745257275088548364400416034343698204186575808495617");
        int n = vk.domainSize();
        BigInteger omega = vk.w();

        // Pick a random evaluation point NOT in the domain
        BigInteger zeta = BigInteger.valueOf(12345678);

        // Compute L_i(zeta) for all i and verify they sum to 1
        BigInteger zetaPowN = zeta.modPow(BigInteger.valueOf(n), bn254_r);
        BigInteger zh = zetaPowN.subtract(BigInteger.ONE).mod(bn254_r);
        BigInteger nInv = BigInteger.valueOf(n).modInverse(bn254_r);

        BigInteger sum = BigInteger.ZERO;
        for (int i = 0; i < n; i++) {
            BigInteger omegaI = omega.modPow(BigInteger.valueOf(i), bn254_r);
            BigInteger li = zh.multiply(nInv).mod(bn254_r)
                    .multiply(omegaI).mod(bn254_r)
                    .multiply(zeta.subtract(omegaI).mod(bn254_r).modInverse(bn254_r)).mod(bn254_r);
            sum = sum.add(li).mod(bn254_r);
        }
        assertEquals(BigInteger.ONE, sum, "Sum of all Lagrange polynomials at any point must be 1");
    }

    // --- Helpers ---

    private static void enableLegacyBn254() {
        System.setProperty(LegacyCurvePolicy.ALLOW_LEGACY_BN254_PROPERTY, "true");
    }

    private ZkProofEnvelope buildEnvelope(String proofJson, String vkJson, String publicJson) {
        return SnarkjsPlonkCodec.toEnvelopeFromJson(proofJson, vkJson, publicJson, new CircuitId("multiplier"));
    }

    private VerificationMaterial buildMaterial(String vkJson) {
        byte[] vkBytes = vkJson.getBytes(StandardCharsets.UTF_8);
        byte[] vkHash;
        try {
            vkHash = MessageDigest.getInstance("SHA-256").digest(vkBytes);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return VerificationMaterial.of(vkBytes, ProofSystemId.PLONK, CurveId.BN254,
                new CircuitId("multiplier"), vkHash);
    }

    private String loadString(String resource) {
        try (var in = getClass().getResourceAsStream(resource)) {
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (Exception e) {
            throw new RuntimeException("Failed to load: " + resource, e);
        }
    }
}
