package org.zeroj.examples.annotation;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.zeroj.api.CircuitId;
import org.zeroj.api.CurveId;
import org.zeroj.api.ProofSystemId;
import org.zeroj.api.VerificationMaterial;
import org.zeroj.circuit.CircuitBuilder;
import org.zeroj.circuit.lib.jubjub.JubjubPoint;
import org.zeroj.circuit.lib.jubjub.PedersenCommitment;
import org.zeroj.circuit.lib.jubjub.PedersenVectorCommitment;
import org.zeroj.codec.SnarkjsJsonCodec;
import org.zeroj.crypto.groth16.Groth16Keys;
import org.zeroj.crypto.snarkjs.SnarkjsGroth16Json;
import org.zeroj.verifier.groth16.bls12381.Groth16BLS12381PureJavaVerifier;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * ADR-0051 through the annotation path: {@code @ZKCircuit} classes using the homomorphic
 * ({@code ZkPedersenCommitment}, {@code ZkPedersen.assertBalanced}) and vector
 * ({@code ZkPedersenVector}) APIs, generated by the annotation processor, proved with Groth16 and
 * verified from serialised JSON.
 */
class AnnotatedPedersenProfilesTest {

    private static final SecureRandom RANDOM = new SecureRandom();

    // ------------------------------------------------------------------
    //  Confidential transfer: in = out + fee
    // ------------------------------------------------------------------

    @Test
    @DisplayName("Annotated confidential transfer: honest witness accepted; wrong fee or commitment rejected; BN254 refused")
    void confidentialTransferWitness() {
        var circuit = AnnotatedConfidentialTransferCircuit.build();
        var honest = transfer(1_000, 990, 10);
        assertDoesNotThrow(() -> circuit.calculateWitness(honest.toWitnessMap(), CurveId.BLS12_381));

        var wrongFee = transfer(1_000, 990, 10).fee(11);
        assertThrows(ArithmeticException.class,
                () -> circuit.calculateWitness(wrongFee.toWitnessMap(), CurveId.BLS12_381));

        var unbalanced = transfer(1_000, 991, 10);
        assertThrows(ArithmeticException.class,
                () -> circuit.calculateWitness(unbalanced.toWitnessMap(), CurveId.BLS12_381));

        var wrongCommitment = transfer(1_000, 990, 10);
        JubjubPoint other = PedersenCommitment.commit(BigInteger.valueOf(990), blinding()).normalized();
        wrongCommitment.outU(other.affineU()).outV(other.affineV());
        assertThrows(ArithmeticException.class,
                () -> circuit.calculateWitness(wrongCommitment.toWitnessMap(), CurveId.BLS12_381));

        assertThrows(IllegalStateException.class, () -> circuit.compileR1CS(CurveId.BN254));
    }

    @Test
    @DisplayName("Annotated confidential transfer: Groth16 proof verifies; a changed fee is rejected")
    void confidentialTransferProof() throws Exception {
        var circuit = AnnotatedConfidentialTransferCircuit.build();
        var inputs = transfer(5_000, 4_750, 250);
        List<BigInteger> publicInputs = AnnotatedConfidentialTransferCircuit.publicInputs(inputs);
        var proof = prove(circuit, inputs.toWitnessMap());
        assertTrue(verify(proof, publicInputs, "annotation-confidential-transfer"));

        List<BigInteger> changedFee = new ArrayList<>(publicInputs);
        changedFee.set(4, BigInteger.valueOf(251));
        assertFalse(verify(proof, changedFee, "annotation-confidential-transfer"));
    }

    // ------------------------------------------------------------------
    //  Vector commitment under a fixed schema
    // ------------------------------------------------------------------

    @Test
    @DisplayName("Annotated vector commitment: honest witness accepted; wrong digest or out-of-width value rejected")
    void vectorCommitmentWitness() {
        var circuit = AnnotatedVectorCommitmentCircuit.build();
        assertDoesNotThrow(() -> circuit.calculateWitness(vector(1_000_000, 7).toWitnessMap(), CurveId.BLS12_381));

        var wrongDigest = vector(1_000_000, 7).schemaDigest(AnnotatedVectorCommitment.SCHEMA.digest().add(BigInteger.ONE));
        assertThrows(ArithmeticException.class,
                () -> circuit.calculateWitness(wrongDigest.toWitnessMap(), CurveId.BLS12_381));

        BigInteger r = blinding();
        var c = PedersenVectorCommitment.commit(AnnotatedVectorCommitment.SCHEMA,
                List.of(BigInteger.ONE, BigInteger.ONE), r);
        var tooWide = AnnotatedVectorCommitmentCircuit.inputs()
                .amount(1).asset(BigInteger.ONE.shiftLeft(32)).blinding(r)
                .schemaDigest(AnnotatedVectorCommitment.SCHEMA.digest())
                .u(c.point().affineU()).v(c.point().affineV());
        assertThrows(ArithmeticException.class,
                () -> circuit.calculateWitness(tooWide.toWitnessMap(), CurveId.BLS12_381));
    }

    @Test
    @DisplayName("Annotated vector commitment: Groth16 proof verifies; another schema's digest is rejected")
    void vectorCommitmentProof() throws Exception {
        var circuit = AnnotatedVectorCommitmentCircuit.build();
        var inputs = vector(42, 3);
        List<BigInteger> publicInputs = AnnotatedVectorCommitmentCircuit.publicInputs(inputs);
        var proof = prove(circuit, inputs.toWitnessMap());
        assertTrue(verify(proof, publicInputs, "annotation-vector-commitment"));

        List<BigInteger> otherSchema = new ArrayList<>(publicInputs);
        otherSchema.set(0, AnnotatedVectorCommitment.SCHEMA.digest().add(BigInteger.ONE));
        assertFalse(verify(proof, otherSchema, "annotation-vector-commitment"));
    }

    // ------------------------------------------------------------------
    //  Harness
    // ------------------------------------------------------------------

    private record Proved(String proofJson, String vkJson) {}

    private static AnnotatedConfidentialTransferCircuit.Inputs transfer(long in, long out, long fee) {
        BigInteger rIn = blinding();
        BigInteger rOut = blinding();
        JubjubPoint cIn = PedersenCommitment.commit(BigInteger.valueOf(in), rIn).normalized();
        JubjubPoint cOut = PedersenCommitment.commit(BigInteger.valueOf(out), rOut).normalized();
        return AnnotatedConfidentialTransferCircuit.inputs()
                .inAmount(in).inBlinding(rIn).outAmount(out).outBlinding(rOut)
                .inU(cIn.affineU()).inV(cIn.affineV())
                .outU(cOut.affineU()).outV(cOut.affineV())
                .fee(fee);
    }

    private static AnnotatedVectorCommitmentCircuit.Inputs vector(long amount, long asset) {
        BigInteger r = blinding();
        var c = PedersenVectorCommitment.commit(AnnotatedVectorCommitment.SCHEMA,
                List.of(BigInteger.valueOf(amount), BigInteger.valueOf(asset)), r);
        return AnnotatedVectorCommitmentCircuit.inputs()
                .amount(amount).asset(asset).blinding(r)
                .schemaDigest(AnnotatedVectorCommitment.SCHEMA.digest())
                .u(c.point().affineU()).v(c.point().affineV());
    }

    private static Proved prove(CircuitBuilder circuit, Map<String, List<BigInteger>> witnessMap) {
        var r1cs = circuit.compileR1CS(CurveId.BLS12_381);
        var keys = Groth16Keys.setupInMemory(r1cs.constraints(), r1cs.numWires(), r1cs.numPublicInputs(),
                BigInteger.valueOf(0xa11cL));
        BigInteger[] witness = circuit.calculateWitness(witnessMap, CurveId.BLS12_381);
        var proof = keys.prove(witness, r1cs.constraints());
        return new Proved(SnarkjsGroth16Json.proofJson(proof), SnarkjsGroth16Json.verificationKeyJson(keys));
    }

    private static boolean verify(Proved proved, List<BigInteger> publicInputs, String name) {
        var circuitId = new CircuitId(name);
        String publicJson = SnarkjsGroth16Json.publicJson(publicInputs.toArray(new BigInteger[0]));
        var envelope = SnarkjsJsonCodec.toEnvelopeFromJson(proved.proofJson(), proved.vkJson(), publicJson, circuitId);
        var material = VerificationMaterial.of(proved.vkJson().getBytes(StandardCharsets.UTF_8),
                ProofSystemId.GROTH16, CurveId.BLS12_381, circuitId);
        return new Groth16BLS12381PureJavaVerifier().verify(envelope, material).proofValid();
    }

    private static BigInteger blinding() {
        return PedersenCommitment.randomBlinding(RANDOM);
    }
}
