package com.bloxbean.cardano.zeroj.prover.wasm;

import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Source;
import org.graalvm.polyglot.Value;
import org.graalvm.polyglot.proxy.ProxyExecutable;

import java.io.IOException;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/**
 * Calculates circom circuit witnesses using GraalVM's WebAssembly runtime.
 *
 * <p>This replaces the Node.js/snarkjs dependency for witness calculation. Given a
 * circom-compiled {@code .wasm} file and input signals, it computes the full witness
 * (all intermediate signals) entirely within the JVM.</p>
 *
 * <p>Usage:</p>
 * <pre>{@code
 * var calculator = new WasmWitnessCalculator(Path.of("multiplier.wasm"));
 * Map<String, List<BigInteger>> inputs = Map.of(
 *     "a", List.of(BigInteger.valueOf(3)),
 *     "b", List.of(BigInteger.valueOf(11)));
 * BigInteger[] witness = calculator.calculateWitness(inputs);
 * // witness = [1, 33, 3, 11]
 * }</pre>
 *
 * <p>Requires GraalVM with WASM support ({@code org.graalvm.polyglot:wasm}).</p>
 */
public class WasmWitnessCalculator implements AutoCloseable {

    private final Context context;
    private final Value exports;
    private final int n32; // number of 32-bit limbs per field element
    private final BigInteger prime;

    /**
     * Create a witness calculator from a circom-compiled WASM file.
     *
     * @param wasmPath path to the .wasm file generated by circom
     */
    public WasmWitnessCalculator(Path wasmPath) throws IOException {
        this(Files.readAllBytes(wasmPath));
    }

    /**
     * Create a witness calculator from WASM bytes.
     *
     * @param wasmBytes the raw .wasm binary content
     */
    public WasmWitnessCalculator(byte[] wasmBytes) {
        this.context = Context.newBuilder("wasm", "js")
                .allowAllAccess(true)
                .allowExperimentalOptions(true)
                .option("wasm.Builtins", "wasi_snapshot_preview1")
                .option("js.webassembly", "true")
                .build();

        try {
            // Use JavaScript WebAssembly API to instantiate with proper imports.
            // circom WASM requires imports from "runtime" namespace.
            // Convert Java byte[] to JS Uint8Array for WebAssembly.Module
            context.getBindings("js").putMember("wasmBytesJava", wasmBytes);

            Value jsExports = context.eval("js", """
                (function() {
                    // Convert Java byte[] to Uint8Array
                    var len = wasmBytesJava.length;
                    var buf = new ArrayBuffer(len);
                    var view = new Uint8Array(buf);
                    for (var i = 0; i < len; i++) {
                        view[i] = wasmBytesJava[i] & 0xFF;
                    }

                    var importObject = {
                        env: { memory: new WebAssembly.Memory({initial: 256}) },
                        runtime: {
                            exceptionHandler: function(code) {
                                throw new Error('Circuit error code: ' + code);
                            },
                            printErrorMessage: function() {},
                            writeBufferMessage: function() {},
                            showSharedRWMemory: function() {}
                        }
                    };
                    var mod = new WebAssembly.Module(buf);
                    var instance = new WebAssembly.Instance(mod, importObject);
                    return instance.exports;
                })()
                """);

            if (jsExports == null || jsExports.isNull()) {
                throw new IllegalStateException("WASM instantiation returned null");
            }
            this.exports = jsExports;

            // Read field parameters
            this.n32 = exports.getMember("getFieldNumLen32").execute().asInt();

            // Read the field prime
            exports.getMember("getRawPrime").execute();
            this.prime = readSharedRWMemory();

        } catch (Exception e) {
            context.close();
            throw new RuntimeException("Failed to initialize WASM witness calculator: " + e.getMessage(), e);
        }
    }

    /**
     * Calculate the witness for the given input signals.
     *
     * @param inputs map of signal name → values (most signals have a single value;
     *               array signals have multiple values indexed from 0)
     * @return the full witness as an array of field elements
     */
    public BigInteger[] calculateWitness(Map<String, List<BigInteger>> inputs) {
        return calculateWitness(inputs, true);
    }

    /**
     * Calculate the witness with optional sanity checking.
     *
     * @param inputs       input signals
     * @param sanityCheck  if true, circom runs constraint checks during witness generation
     * @return the full witness
     */
    public BigInteger[] calculateWitness(Map<String, List<BigInteger>> inputs, boolean sanityCheck) {
        // Initialize the circuit
        exports.getMember("init").execute(sanityCheck ? 1 : 0);

        // Set all input signals
        for (var entry : inputs.entrySet()) {
            String signalName = entry.getKey();
            List<BigInteger> values = entry.getValue();

            // Compute FNV-1a hash of signal name
            long hash = fnvHash(signalName);
            int hMSB = (int) (hash >>> 32);
            int hLSB = (int) (hash & 0xFFFFFFFFL);

            for (int idx = 0; idx < values.size(); idx++) {
                BigInteger value = values.get(idx).mod(prime);
                writeSharedRWMemory(value);
                exports.getMember("setInputSignal").execute(hMSB, hLSB, idx);
            }
        }

        // Read all witness values
        int witnessSize = exports.getMember("getWitnessSize").execute().asInt();
        BigInteger[] witness = new BigInteger[witnessSize];

        for (int i = 0; i < witnessSize; i++) {
            exports.getMember("getWitness").execute(i);
            witness[i] = readSharedRWMemory();
        }

        return witness;
    }

    /**
     * Calculate witness and export as .wtns binary format.
     */
    public byte[] calculateWtns(Map<String, List<BigInteger>> inputs) {
        BigInteger[] witness = calculateWitness(inputs);
        return WitnessExporter.toWtns(witness, prime, n32);
    }

    /**
     * Get the number of witness elements for this circuit.
     */
    public int getWitnessSize() {
        return exports.getMember("getWitnessSize").execute().asInt();
    }

    /**
     * Get the number of input signals for this circuit.
     */
    public int getInputSize() {
        return exports.getMember("getInputSize").execute().asInt();
    }

    /**
     * Get the field prime for this circuit.
     */
    public BigInteger getPrime() {
        return prime;
    }

    /**
     * Get the circom version that compiled this circuit.
     */
    public int getVersion() {
        return exports.getMember("getVersion").execute().asInt();
    }

    @Override
    public void close() {
        context.close();
    }

    // --- Internal: shared R/W memory protocol ---

    /**
     * Write a BigInteger value to the WASM shared R/W memory as n32 limbs.
     * Follows the circom convention: limbs written in reverse order (LSB first in memory).
     */
    private void writeSharedRWMemory(BigInteger value) {
        int[] limbs = bigIntToLimbs(value, n32);
        for (int j = 0; j < n32; j++) {
            exports.getMember("writeSharedRWMemory").execute(j, limbs[n32 - 1 - j]);
        }
    }

    /**
     * Read a BigInteger value from the WASM shared R/W memory.
     */
    private BigInteger readSharedRWMemory() {
        int[] limbs = new int[n32];
        for (int j = 0; j < n32; j++) {
            limbs[n32 - 1 - j] = exports.getMember("readSharedRWMemory").execute(j).asInt();
        }
        return limbsToBigInt(limbs);
    }

    /**
     * Decompose a BigInteger into an array of unsigned 32-bit limbs (big-endian order).
     */
    static int[] bigIntToLimbs(BigInteger value, int n32) {
        int[] limbs = new int[n32];
        BigInteger mask = BigInteger.valueOf(0xFFFFFFFFL);
        for (int i = n32 - 1; i >= 0; i--) {
            limbs[i] = value.and(mask).intValue();
            value = value.shiftRight(32);
        }
        return limbs;
    }

    /**
     * Reconstruct a BigInteger from unsigned 32-bit limbs (big-endian order).
     */
    static BigInteger limbsToBigInt(int[] limbs) {
        BigInteger result = BigInteger.ZERO;
        for (int i = 0; i < limbs.length; i++) {
            result = result.shiftLeft(32).or(BigInteger.valueOf(limbs[i] & 0xFFFFFFFFL));
        }
        return result;
    }

    /**
     * FNV-1a hash of a signal name, matching circom's convention.
     * Returns a 64-bit hash value.
     */
    static long fnvHash(String name) {
        long hash = 0xCBF29CE484222325L; // FNV-1a offset basis
        long fnvPrime = 0x100000001B3L;   // FNV prime
        for (int i = 0; i < name.length(); i++) {
            hash ^= name.charAt(i);
            hash *= fnvPrime; // Java long overflow wraps like uint64
        }
        return hash;
    }

}
