package com.bloxbean.cardano.zeroj.crypto.groth16;

import com.bloxbean.cardano.zeroj.crypto.ec.JacobianG1BN254.AffineG1;
import com.bloxbean.cardano.zeroj.crypto.ec.JacobianG2BN254.AffineG2;

/**
 * Groth16 proving key for BN254.
 *
 * <p>Contains the encrypted evaluation points from the trusted setup ceremony.
 * This is NOT generated by the pure Java prover — it is imported from snarkjs
 * or gnark output.</p>
 *
 * @param alpha   alpha in G1
 * @param beta    beta in G1 and G2
 * @param delta   delta in G1 and G2
 * @param pointsA A_i(tau) in G1, one per wire (indices 0..numWires-1)
 * @param pointsB1 B_i(tau) in G1 (for computing C)
 * @param pointsB2 B_i(tau) in G2 (for proof element B)
 * @param pointsH  H_i(tau) in G1, coset evaluations for h(x) polynomial
 * @param pointsL  L_j(tau) in G1, for private witness wires only
 * @param numPublic number of public inputs (wires 1..numPublic are public)
 */
public record Groth16ProvingKey(
        AffineG1 alphaG1,
        AffineG1 betaG1,
        AffineG2 betaG2,
        AffineG1 deltaG1,
        AffineG2 deltaG2,
        AffineG1[] pointsA,   // [numWires] — A_i(tau) in G1
        AffineG1[] pointsB1,  // [numWires] — B_i(tau) in G1
        AffineG2[] pointsB2,  // [numWires] — B_i(tau) in G2
        AffineG1[] pointsH,   // [domainSize] — H_i coset evaluations in G1
        AffineG1[] pointsL,   // [numPrivate] — L_j(tau) in G1 (private wires only)
        int numPublic
) {}
